micronaut:
  application:
    name: fjCryptoBot

micronaut:

bot: {
  name: "telegramBotName",
  token: "telegramBotToken",
}
api: {
  token: "CoinMarketCapToken"
}

fns: {
  device: "DeviceId",
  os: "Linux",
  login: "Login",
  password: "Password"
}



